### PR TITLE
F/wep 136 richtext toolbar style

### PR DESCRIPTION
**Pull request by faebebin**
Thanks for all the previous reviews. The bug discovered by @roosnic1 (see below) let me rethink the behaviour of the submenu popovers. So now they close when a new editor is focused. I think the behaviour now makes sense.

### CODE REVIEW

**Review by bishoymelek — APPROVED** [review]

**Review by 0815pascal — APPROVED** [review]
Looks good 👍🏼

**Review by roosnic1 — COMMENTED** [review]
Superb work. Just a little UI bug i found:

deepin-screen-recorder_Select area_20201221144607
Not sure if that's only happening in Firefox.

**Comment by faebebin** [comment]
> Superb work. Just a little UI bug i found:
> 
> deepin-screen-recorder_Select area_20201221144607
> Not sure if that's only happening in Firefox.

nop, happening on chrome too. Need to fix anyway :)

**Review by penk85 — DISMISSED** [review]

**Review by roosnic1 — APPROVED** [review]
Awesome ⭐

**Review by bishoymelek — APPROVED** [review]

**Pull request merged**
