### PR TITLE
Media adapter improvement and testing

### PR DESCRIPTION
**Pull request by roosnic1**
Added a method to add images by arrayBuffer and setup jest for testing. This should be an example for the other packages.

### Testing

- [x] fresh clone and install and setup command
- [x] run build
- [x] run test locally
- [ ] upload image locally (related to e22 tesing)
- [x] comments in test setup.ts file
- [x] use super small test image

### CODE REVIEW

**Review by penk85 — APPROVED** [review]

**Review by 0815pascal — APPROVED** [review]

**Review by dev7ch — COMMENTED** [review]
- Was able to run all newly added scripts locally (after install) 👍 
- but while uploading an image loccally i got an error, Connection refused

**Comment by dev7ch** [comment]
so the media servers is accessible locally vai port :3004, this is the console output:

image

**Comment by dev7ch** [comment]
can you upload images locally @roosnic1?

**Comment by roosnic1** [comment]
@dev7ch yes it works fine on my machine. Pretty sure it's the media server that has a hiccup and has nothing to do with the upload.

**Review by dev7ch — APPROVED** [review]

**Pull request merged**
