### PR TITLE
resolve auto open gallery on save

### PR DESCRIPTION
**Pull request by penk85**
WPC-618: Resolve bug where gallery drawer was opening after saving an article.

### CODE REVIEW

**Review by camilleory — APPROVED** [review]

**Review by roosnic1 — APPROVED** [review]
🎉

**Review by tomaszdurka — APPROVED** [review]

**Review by bishoymelek — APPROVED** [review]
🎉

**Review by roosnic1 — APPROVED** [review]
💯

**Review by tomaszdurka — APPROVED** [review]
looks good to me

**Pull request merged**
