### PR TITLE
wpc-305-change-unpublish-icon

### PR DESCRIPTION
**Pull request by HanaAyman**

### CODE REVIEW

**Review by bishoymelek — APPROVED** [review]

**Review by penk85 — APPROVED** [review]
Works nicely, but curious what you think about power-off icon or stop icon for a bit of a lighter feel?

**Review by roosnic1 — APPROVED** [review]
👍🏾

**Comment by HanaAyman** [comment]
> Works nicely, but curious what you think about power-off icon or stop icon for a bit of a lighter feel?

**Comment by HanaAyman** [comment]
@penk85 This icon is the one Laurent chose, will check with him 👍 Thank you.

**Comment by HanaAyman** [comment]
> Works nicely, but curious what you think about power-off icon or stop icon for a bit of a lighter feel?

@penk85 This icon is the one Laurent chose, will check with him 👍 Thank you.

**Pull request merged**
