### PR TITLE
chore(editor): upgrade i18next

### PR DESCRIPTION
**Pull request by Itrulia**

### CODE REVIEW

**Comment by antkiewiczk** [comment]
from what I see in docs, in the freshest version (23) of i18next `returnNull` is set to `false` by default so there should be no need for a rewrite like this IMO, at least if I understand this correctly. Would prefer not to rewrite all translations to return `xxx || undefined` if it isn't absolutely necessary

**Comment by antkiewiczk** [comment]
Screenshot 2023-06-16 at 10 33 20

https://github.com/i18next/i18next/issues/1884

**Comment by Itrulia** [comment]
That release came 1 day ago! God damnit.

**Comment by Itrulia** [comment]
Upgraded to v23, discarded most of the changes

**Review by antkiewiczk — APPROVED** [review]

**Pull request merged**
